{% set name = "smqtk-classifier" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smqtk_classifier-{{ version }}.tar.gz
  sha256: f09750dc32d0c66e1ac8cfb5fb180dc7185fe48749bb71ca00426acb4e1ea2e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.8,<4.0
    - numpy >=1.19.5,<2.0.0
    - smqtk-core >=0.18.0
    - smqtk-dataprovider >=0.16.0
    - smqtk-descriptors >=0.18

test:
  imports:
    - smqtk_classifier
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kitware/SMQTK-Classifier
  summary: Algorithms, data structures and utilities around performing classification of inputs.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Purg
    - barry-ravichandran
