{% set name = "smqtk-classifier" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smqtk_classifier-{{ version }}.tar.gz
  sha256: bd888e5eb718592b922cf24ea524ffad08f24c06e6203f638c6a2aeb5304f632

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.19.5,<2.0.0
    - smqtk-core >=0.18.0
    - smqtk-dataprovider >=0.16.0
    - smqtk-descriptors >=0.18

test:
  imports:
    - smqtk_classifier
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kitware/SMQTK-Classifier
  summary: Algorithms, data structures and utilities around performing classification of inputs.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Purg
    - barry-ravichandran
